# Generated by Django 4.2.26 on 2026-05-18 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('comentario', models.TextField(max_length=1000)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'comentarios_plato',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad', models.CharField(default='ud', max_length=20)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('umbral_alerta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('disposicion', models.CharField(default='interior', max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('reservada', 'Reservada'), ('mantenimiento', 'Mantenimiento')], default='libre', max_length=20)),
            ],
            options={
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('es_vegano', models.BooleanField(default=False)),
                ('es_halal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'platos',
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL destino para el webhook')),
                ('event_type', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('pedido_completado', 'Pedido Completado'), ('pedido_cancelado', 'Pedido Cancelado'), ('nueva_valoracion', 'Nueva Valoración'), ('reserva_confirmada', 'Reserva Confirmada'), ('alerta_ingrediente', 'Alerta de Ingrediente')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('secret_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Subscription',
                'verbose_name_plural': 'Webhook Subscriptions',
                'unique_together': {('user', 'url', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('payload', models.JSONField(help_text='Datos del evento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('delivered', 'Entregado')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='restaurante.webhooksubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(help_text='Tiempo de respuesta en milisegundos')),
                ('error_message', models.TextField(blank=True)),
                ('headers_sent', models.JSONField()),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='restaurante.webhookevent')),
            ],
            options={
                'verbose_name_plural': 'Webhook Delivery Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='restaurante.comentarioplato')),
            ],
            options={
                'db_table': 'votos_comentario',
            },
        ),
        migrations.CreateModel(
            name='ValoracionPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254)),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='restaurante.plato')),
            ],
            options={
                'db_table': 'valoraciones_plato',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(default='', max_length=254)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('pedido_anticipado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='restaurante.mesa')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='restaurante.ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='restaurante.plato')),
            ],
            options={
                'db_table': 'recetas',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='empleado', max_length=20)),
                ('tema', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('idioma', models.CharField(choices=[('es', 'Espanol'), ('en', 'English')], default='es', max_length=2)),
                ('nombre_mostrar', models.CharField(blank=True, default='', max_length=120)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato_texto', models.CharField(db_column='plato', default='', max_length=150)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_limite', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredientes_descontados', models.BooleanField(default=False)),
                ('preparado_en', models.DateTimeField(blank=True, null=True)),
                ('listo_en', models.DateTimeField(blank=True, null=True)),
                ('plato', models.ForeignKey(blank=True, db_column='plato_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='restaurante.plato')),
                ('preparado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_preparados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante.reserva')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('establecimiento', 'Pago en establecimiento'), ('bizum', 'Bizum'), ('tarjeta', 'Tarjeta')], default='establecimiento', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=80)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='restaurante.reserva')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.AddField(
            model_name='comentarioplato',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='restaurante.plato'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='restaurante_status_cc1b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['created_at'], name='restaurante_created_e1c32e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votocomentario',
            unique_together={('comentario', 'email_cliente')},
        ),
        migrations.AlterUniqueTogether(
            name='valoracionplato',
            unique_together={('plato', 'email_cliente')},
        ),
        migrations.AlterUniqueTogether(
            name='receta',
            unique_together={('plato', 'ingrediente')},
        ),
    ]
