# Generated by Django 4.2.26 on 2026-05-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_webhooks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='restaurante_status_cc1b1a_idx',
            old_name='restaurante_status_next_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='restaurante_created_e1c32e_idx',
            old_name='restaurante_created_idx',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='empleado', max_length=20),
        ),
    ]
